# Generated by Django 5.1.7 on 2025-03-29 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('voltage', models.FloatField(help_text='الجهد الكهربائي للمصدر بالفولت')),
                ('connection_tool', models.CharField(help_text='حدد نوع أداة التوصيل (الكابل) لمصدر الطاقة', max_length=50)),
                ('load_coefficient', models.FloatField(default=1.0, help_text='معامل تحميل المصدر')),
            ],
        ),
        migrations.CreateModel(
            name='MainPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_tool', models.CharField(help_text='حدد أداة التوصيل للوحة الرئيسية (نوع الكابل المستخدم)', max_length=50)),
                ('power_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_panels', to='network.powersource')),
            ],
        ),
        migrations.CreateModel(
            name='SubPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_tool', models.CharField(help_text='حدد أداة التوصيل للوحة الفرعية', max_length=50)),
                ('main_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_panels', to='network.mainpanel')),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('connection_tool', models.CharField(help_text='حدد أداة التوصيل للحمل (نوع الكابل المستخدم)', max_length=50)),
                ('power_consumption', models.FloatField(default=0, help_text='استهلاك الطاقة بالواط')),
                ('sub_panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='network.subpanel')),
            ],
        ),
    ]
