# Generated by Django 5.1.7 on 2025-03-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='ampacity',
            field=models.FloatField(default=0, help_text='الأمبير الكلي'),
        ),
        migrations.AddField(
            model_name='load',
            name='breaker_specifications',
            field=models.JSONField(default=dict, help_text='Specifications: number_of_poles, model, manufacturer, recommended_brands, Isc, Iload'),
        ),
        migrations.AddField(
            model_name='load',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="Cable data: quantity, conductor_cross_section (e.g., '3x300+185')"),
        ),
        migrations.AddField(
            model_name='load',
            name='feeding_source_type',
            field=models.CharField(choices=[('MP', 'Main Panel'), ('SP', 'Sub Panel')], default='SP', help_text='نوع مصدر التغذية - لوحة رئيسية أو فرعية', max_length=2),
        ),
        migrations.AddField(
            model_name='load',
            name='main_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads_from_main', to='network.mainpanel'),
        ),
        migrations.AddField(
            model_name='load',
            name='voltage',
            field=models.FloatField(default=0, help_text='الجهد بالفولت'),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='ampacity',
            field=models.FloatField(default=0, help_text='الأمبير الكلي'),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='breaker_specifications',
            field=models.JSONField(default=dict, help_text='Specifications: number_of_poles, model, manufacturer, recommended_brands, Isc, Iload'),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="Cable data: quantity, conductor_cross_section (e.g., '3x300+185')"),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='new_sub_breaker_data',
            field=models.JSONField(blank=True, help_text='بيانات لإضافة قاطع فرعي جديد', null=True),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='voltage',
            field=models.FloatField(default=0, help_text='الجهد بالفولت'),
        ),
        migrations.AddField(
            model_name='powersource',
            name='breaker_specifications',
            field=models.JSONField(default=dict, help_text='Specifications: number_of_poles, model, manufacturer, recommended_brands, Isc, Iload'),
        ),
        migrations.AddField(
            model_name='powersource',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="Cable data: quantity, conductor_cross_section (e.g., '3x300+185')"),
        ),
        migrations.AddField(
            model_name='powersource',
            name='new_breaker_data',
            field=models.JSONField(blank=True, help_text='Data for adding a new circuit breaker', null=True),
        ),
        migrations.AddField(
            model_name='powersource',
            name='source_type',
            field=models.CharField(default='Local Grid', help_text="Options: 'Local Grid' or 'Generator'", max_length=50),
        ),
        migrations.AddField(
            model_name='powersource',
            name='total_ampacity',
            field=models.FloatField(default=0, help_text='الأمبير الكلي بالأمبير'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='ampacity',
            field=models.FloatField(default=0, help_text='الأمبير الكلي'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='breaker_specifications',
            field=models.JSONField(default=dict, help_text='Specifications: number_of_poles, model, manufacturer, recommended_brands, Isc, Iload'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="Cable data: quantity, conductor_cross_section (e.g., '3x300+185')"),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='new_sub_breaker_data',
            field=models.JSONField(blank=True, help_text='بيانات لإضافة قاطع فرعي جديد', null=True),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='voltage',
            field=models.FloatField(default=0, help_text='الجهد بالفولت'),
        ),
        migrations.AlterField(
            model_name='load',
            name='connection_tool',
            field=models.CharField(default='', help_text='حدد أداة التوصيل للحمل (نوع الكابل المستخدم)', max_length=50),
        ),
        migrations.AlterField(
            model_name='load',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='sub_panel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='network.subpanel'),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='connection_tool',
            field=models.CharField(default='', help_text='حدد أداة التوصيل للوحة الرئيسية (نوع الكابل المستخدم)', max_length=50),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='connection_tool',
            field=models.CharField(default='', help_text='حدد نوع أداة التوصيل (الكابل) لمصدر الطاقة', max_length=50),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='connection_tool',
            field=models.CharField(default='', help_text='حدد أداة التوصيل للوحة الفرعية', max_length=50),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
