# Generated by Django 5.1.7 on 2025-03-29 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_load_ampacity_load_breaker_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powersource',
            name='breaker_specifications',
        ),
        migrations.RemoveField(
            model_name='powersource',
            name='new_breaker_data',
        ),
        migrations.AlterField(
            model_name='load',
            name='breaker_specifications',
            field=models.JSONField(default=dict, help_text='مواصفات القاطع: عدد الأقطاب، الموديل، الشركة المصنعة، العلامات التجارية الموصى بها، تيار القصر، تيار الحمل'),
        ),
        migrations.AlterField(
            model_name='load',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="بيانات الكابلات: الكمية، مقطع الموصل (مثال: '3x300+185')"),
        ),
        migrations.AlterField(
            model_name='load',
            name='feeding_source_type',
            field=models.CharField(choices=[('MP', 'لوحة رئيسية'), ('SP', 'لوحة فرعية')], default='SP', help_text='نوع مصدر التغذية - لوحة رئيسية أو فرعية', max_length=2),
        ),
        migrations.AlterField(
            model_name='load',
            name='main_panel',
            field=models.ForeignKey(blank=True, help_text='اللوحة الرئيسية المغذية (في حالة اختيار لوحة رئيسية كمصدر)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads_from_main', to='network.mainpanel'),
        ),
        migrations.AlterField(
            model_name='load',
            name='name',
            field=models.CharField(help_text='اسم الحمل', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='load',
            name='sub_panel',
            field=models.ForeignKey(blank=True, help_text='اللوحة الفرعية المغذية (في حالة اختيار لوحة فرعية كمصدر)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='network.subpanel'),
        ),
        migrations.AlterField(
            model_name='load',
            name='voltage',
            field=models.CharField(choices=[('11KV', '11 كيلو فولت'), ('380', '380 فولت'), ('220', '220 فولت'), ('24', '24 فولت')], default='220', help_text='الجهد الكهربائي', max_length=10),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='breaker_specifications',
            field=models.JSONField(default=dict, help_text='مواصفات القاطع: عدد الأقطاب، الموديل، الشركة المصنعة، العلامات التجارية الموصى بها، تيار القصر، تيار الحمل'),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="بيانات الكابلات: الكمية، مقطع الموصل (مثال: '3x300+185')"),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='name',
            field=models.CharField(help_text='اسم اللوحة الرئيسية', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='power_source',
            field=models.ForeignKey(help_text='مصدر الطاقة المغذي', on_delete=django.db.models.deletion.CASCADE, related_name='main_panels', to='network.powersource'),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='voltage',
            field=models.CharField(choices=[('11KV', '11 كيلو فولت'), ('380', '380 فولت'), ('220', '220 فولت'), ('24', '24 فولت')], default='220', help_text='الجهد الكهربائي', max_length=10),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="بيانات الكابلات: الكمية، مقطع الموصل (مثال: '3x300+185')"),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='name',
            field=models.CharField(help_text='اسم المصدر', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='source_type',
            field=models.CharField(choices=[('Local Grid', 'الشبكة المحلية'), ('Generator', 'مولد')], default='Local Grid', help_text='نوع المصدر (الشبكة المحلية أو مولد)', max_length=50),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='voltage',
            field=models.CharField(choices=[('11KV', '11 كيلو فولت'), ('380', '380 فولت'), ('220', '220 فولت'), ('24', '24 فولت')], default='220', help_text='الجهد الكهربائي للمصدر', max_length=10),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='breaker_specifications',
            field=models.JSONField(default=dict, help_text='مواصفات القاطع: عدد الأقطاب، الموديل، الشركة المصنعة، العلامات التجارية الموصى بها، تيار القصر، تيار الحمل'),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='feeder_cables',
            field=models.JSONField(default=dict, help_text="بيانات الكابلات: الكمية، مقطع الموصل (مثال: '3x300+185')"),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='main_panel',
            field=models.ForeignKey(help_text='اللوحة الرئيسية المغذية', on_delete=django.db.models.deletion.CASCADE, related_name='sub_panels', to='network.mainpanel'),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='name',
            field=models.CharField(help_text='اسم اللوحة الفرعية', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='voltage',
            field=models.CharField(choices=[('11KV', '11 كيلو فولت'), ('380', '380 فولت'), ('220', '220 فولت'), ('24', '24 فولت')], default='220', help_text='الجهد الكهربائي', max_length=10),
        ),
    ]
