# Generated by Django 5.1.7 on 2025-03-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_powersource_breaker_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='connection_tool',
        ),
        migrations.RemoveField(
            model_name='load',
            name='feeder_cables',
        ),
        migrations.RemoveField(
            model_name='mainpanel',
            name='connection_tool',
        ),
        migrations.RemoveField(
            model_name='mainpanel',
            name='feeder_cables',
        ),
        migrations.RemoveField(
            model_name='powersource',
            name='connection_tool',
        ),
        migrations.RemoveField(
            model_name='powersource',
            name='feeder_cables',
        ),
        migrations.RemoveField(
            model_name='powersource',
            name='load_coefficient',
        ),
        migrations.RemoveField(
            model_name='subpanel',
            name='connection_tool',
        ),
        migrations.RemoveField(
            model_name='subpanel',
            name='feeder_cables',
        ),
        migrations.AddField(
            model_name='load',
            name='cable_cross_section',
            field=models.PositiveIntegerField(default=0, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AddField(
            model_name='load',
            name='cable_length',
            field=models.FloatField(default=0, help_text='طول الكابل (متر)'),
        ),
        migrations.AddField(
            model_name='load',
            name='cable_material',
            field=models.CharField(choices=[('copper', 'نحاس'), ('aluminum', 'ألومنيوم')], default='copper', help_text='نوع مادة الكابل (نحاس أو ألومنيوم)', max_length=10),
        ),
        migrations.AddField(
            model_name='load',
            name='cable_path',
            field=models.CharField(choices=[('aerial', 'في الهواء'), ('buried', 'مدفون'), ('conduit', 'في أنابيب'), ('tray', 'في مجاري كابلات')], default='aerial', help_text='مسار الكابل (في الهواء أو مدفون)', max_length=10),
        ),
        migrations.AddField(
            model_name='load',
            name='cable_quantity',
            field=models.PositiveIntegerField(default=1, help_text='عدد الكابلات'),
        ),
        migrations.AddField(
            model_name='load',
            name='neutral_cross_section',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='cable_cross_section',
            field=models.PositiveIntegerField(default=0, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='cable_length',
            field=models.FloatField(default=0, help_text='طول الكابل (متر)'),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='cable_material',
            field=models.CharField(choices=[('copper', 'نحاس'), ('aluminum', 'ألومنيوم')], default='copper', help_text='نوع مادة الكابل (نحاس أو ألومنيوم)', max_length=10),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='cable_path',
            field=models.CharField(choices=[('aerial', 'في الهواء'), ('buried', 'مدفون'), ('conduit', 'في أنابيب'), ('tray', 'في مجاري كابلات')], default='aerial', help_text='مسار الكابل (في الهواء أو مدفون)', max_length=10),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='cable_quantity',
            field=models.PositiveIntegerField(default=1, help_text='عدد الكابلات'),
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='neutral_cross_section',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
        migrations.AddField(
            model_name='powersource',
            name='cable_cross_section',
            field=models.PositiveIntegerField(default=0, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AddField(
            model_name='powersource',
            name='cable_length',
            field=models.FloatField(default=0, help_text='طول الكابل (متر)'),
        ),
        migrations.AddField(
            model_name='powersource',
            name='cable_material',
            field=models.CharField(choices=[('copper', 'نحاس'), ('aluminum', 'ألومنيوم')], default='copper', help_text='نوع مادة الكابل (نحاس أو ألومنيوم)', max_length=10),
        ),
        migrations.AddField(
            model_name='powersource',
            name='cable_path',
            field=models.CharField(choices=[('aerial', 'في الهواء'), ('buried', 'مدفون'), ('conduit', 'في أنابيب'), ('tray', 'في مجاري كابلات')], default='aerial', help_text='مسار الكابل (في الهواء أو مدفون)', max_length=10),
        ),
        migrations.AddField(
            model_name='powersource',
            name='cable_quantity',
            field=models.PositiveIntegerField(default=1, help_text='عدد الكابلات'),
        ),
        migrations.AddField(
            model_name='powersource',
            name='neutral_cross_section',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='cable_cross_section',
            field=models.PositiveIntegerField(default=0, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='cable_length',
            field=models.FloatField(default=0, help_text='طول الكابل (متر)'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='cable_material',
            field=models.CharField(choices=[('copper', 'نحاس'), ('aluminum', 'ألومنيوم')], default='copper', help_text='نوع مادة الكابل (نحاس أو ألومنيوم)', max_length=10),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='cable_path',
            field=models.CharField(choices=[('aerial', 'في الهواء'), ('buried', 'مدفون'), ('conduit', 'في أنابيب'), ('tray', 'في مجاري كابلات')], default='aerial', help_text='مسار الكابل (في الهواء أو مدفون)', max_length=10),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='cable_quantity',
            field=models.PositiveIntegerField(default=1, help_text='عدد الكابلات'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='neutral_cross_section',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
    ]
