# Generated by Django 5.1.7 on 2025-03-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_load_connection_tool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='cable_cross_section',
            field=models.FloatField(choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=2.5, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AlterField(
            model_name='load',
            name='neutral_cross_section',
            field=models.FloatField(blank=True, choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='cable_cross_section',
            field=models.FloatField(choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=2.5, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AlterField(
            model_name='mainpanel',
            name='neutral_cross_section',
            field=models.FloatField(blank=True, choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='cable_cross_section',
            field=models.FloatField(choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=2.5, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AlterField(
            model_name='powersource',
            name='neutral_cross_section',
            field=models.FloatField(blank=True, choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='cable_cross_section',
            field=models.FloatField(choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=2.5, help_text='مساحة مقطع الكابل (ملم²)'),
        ),
        migrations.AlterField(
            model_name='subpanel',
            name='neutral_cross_section',
            field=models.FloatField(blank=True, choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True),
        ),
    ]
