# Generated by Django 5.1.7 on 2025-03-29 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_load_cable_cross_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='اسم القاطع', max_length=100, null=True)),
                ('model', models.CharField(blank=True, help_text='موديل القاطع', max_length=100, null=True)),
                ('manufacturer', models.CharField(choices=[('ABB', 'ABB'), ('Schneider', 'شنايدر إلكتريك'), ('Siemens', 'سيمنس'), ('Legrand', 'لوجراند'), ('Eaton', 'إيتون'), ('GE', 'جنرال إلكتريك'), ('Havells', 'هافيلس'), ('Chint', 'تشينت'), ('LS', 'LS'), ('Mitsubishi', 'ميتسوبيشي'), ('Hyundai', 'هيونداي'), ('other', 'أخرى')], default='Schneider', help_text='الشركة المصنعة للقاطع', max_length=20)),
                ('breaker_type', models.CharField(choices=[('MCB', 'MCB - قاطع دارة مصغر'), ('MCCB', 'MCCB - قاطع دارة مشكل'), ('ACB', 'ACB - قاطع دارة هوائي'), ('ELCB', 'ELCB - قاطع دارة تسرب أرضي'), ('RCD', 'RCD - جهاز تيار متبقي'), ('RCBO', 'RCBO - قاطع دارة بتيار متبقي')], default='MCB', help_text='نوع القاطع', max_length=10)),
                ('number_of_poles', models.IntegerField(choices=[(1, '1 قطب'), (2, '2 قطب'), (3, '3 أقطاب'), (4, '4 أقطاب')], default=1, help_text='عدد الأقطاب')),
                ('rated_current', models.FloatField(default=0, help_text='التيار المقنن بالأمبير')),
                ('short_circuit_current', models.FloatField(default=0, help_text='تيار القصر (Isc) بالكيلو أمبير')),
                ('trip_curve', models.CharField(default='C', help_text='منحنى الفصل (مثل B، C، D، K)', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='load',
            name='breaker_specifications',
        ),
        migrations.RemoveField(
            model_name='load',
            name='main_panel',
        ),
        migrations.RemoveField(
            model_name='load',
            name='sub_panel',
        ),
        migrations.RemoveField(
            model_name='mainpanel',
            name='breaker_specifications',
        ),
        migrations.RemoveField(
            model_name='mainpanel',
            name='new_sub_breaker_data',
        ),
        migrations.RemoveField(
            model_name='subpanel',
            name='breaker_specifications',
        ),
        migrations.RemoveField(
            model_name='subpanel',
            name='new_sub_breaker_data',
        ),
        migrations.AddField(
            model_name='mainpanel',
            name='main_breaker',
            field=models.OneToOneField(blank=True, help_text='القاطع العمومي للوحة الرئيسية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_panel', to='network.circuitbreaker'),
        ),
        migrations.AddField(
            model_name='powersource',
            name='main_breaker',
            field=models.OneToOneField(blank=True, help_text='القاطع العمومي لمصدر الطاقة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_source', to='network.circuitbreaker'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='main_breaker',
            field=models.OneToOneField(blank=True, help_text='القاطع العمومي للوحة الفرعية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_panel', to='network.circuitbreaker'),
        ),
        migrations.CreateModel(
            name='MainPanelBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='وصف مختصر للقاطع (مثال: إنارة الطابق الأول)', max_length=100, null=True)),
                ('position', models.IntegerField(default=0, help_text='الموقع في اللوحة (الترتيب)')),
                ('breaker', models.OneToOneField(help_text='تفاصيل القاطع الفرعي', on_delete=django.db.models.deletion.CASCADE, related_name='main_panel_sub_breaker', to='network.circuitbreaker')),
                ('main_panel', models.ForeignKey(help_text='اللوحة الرئيسية التي ينتمي إليها القاطع', on_delete=django.db.models.deletion.CASCADE, related_name='sub_breakers', to='network.mainpanel')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='load',
            name='main_panel_breaker',
            field=models.ForeignKey(blank=True, help_text='القاطع المغذي في اللوحة الرئيسية (في حالة التغذية من لوحة رئيسية)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='network.mainpanelbreaker'),
        ),
        migrations.AddField(
            model_name='subpanel',
            name='feeder_breaker',
            field=models.OneToOneField(blank=True, help_text='القاطع المغذي للوحة الفرعية في اللوحة الرئيسية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_panel', to='network.mainpanelbreaker'),
        ),
        migrations.CreateModel(
            name='SubPanelBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='وصف مختصر للقاطع (مثال: مكيف غرفة المعيشة)', max_length=100, null=True)),
                ('position', models.IntegerField(default=0, help_text='الموقع في اللوحة (الترتيب)')),
                ('breaker', models.OneToOneField(help_text='تفاصيل القاطع الفرعي', on_delete=django.db.models.deletion.CASCADE, related_name='sub_panel_sub_breaker', to='network.circuitbreaker')),
                ('sub_panel', models.ForeignKey(help_text='اللوحة الفرعية التي ينتمي إليها القاطع', on_delete=django.db.models.deletion.CASCADE, related_name='sub_breakers', to='network.subpanel')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='load',
            name='sub_panel_breaker',
            field=models.ForeignKey(blank=True, help_text='القاطع المغذي في اللوحة الفرعية (في حالة التغذية من لوحة فرعية)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='network.subpanelbreaker'),
        ),
    ]
