# Generated by Django 5.1.7 on 2025-04-02 12:59

import django.db.models.deletion
import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_circuitbreaker_remove_load_breaker_specifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subpanel',
            name='main_panel',
        ),
        migrations.RemoveField(
            model_name='mainpanelbreaker',
            name='main_panel',
        ),
        migrations.RemoveField(
            model_name='mainpanelbreaker',
            name='breaker',
        ),
        migrations.RemoveField(
            model_name='subpanel',
            name='feeder_breaker',
        ),
        migrations.RemoveField(
            model_name='load',
            name='main_panel_breaker',
        ),
        migrations.RemoveField(
            model_name='subpanel',
            name='main_breaker',
        ),
        migrations.RemoveField(
            model_name='subpanelbreaker',
            name='sub_panel',
        ),
        migrations.RemoveField(
            model_name='subpanelbreaker',
            name='breaker',
        ),
        migrations.RemoveField(
            model_name='load',
            name='sub_panel_breaker',
        ),
        migrations.AlterModelOptions(
            name='circuitbreaker',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='load',
            name='feeding_source_type',
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='breaker_role',
            field=models.CharField(choices=[('main', 'قاطع رئيسي'), ('distribution', 'قاطع توزيع')], default='distribution', help_text='دور القاطع (رئيسي أو توزيع)', max_length=20),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='label',
            field=models.CharField(blank=True, help_text='وصف مختصر للقاطع (مثال: إنارة الطابق الأول)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='position',
            field=models.IntegerField(default=0, help_text='الموقع في اللوحة (الترتيب)'),
        ),
        migrations.AddField(
            model_name='load',
            name='breaker',
            field=models.ForeignKey(blank=True, help_text='القاطع المغذي للحمل', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loads', to='network.circuitbreaker'),
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم اللوحة', max_length=100, unique=True)),
                ('panel_type', models.CharField(choices=[('main', 'لوحة رئيسية'), ('sub', 'لوحة فرعية')], default='main', help_text='نوع اللوحة (رئيسية أو فرعية)', max_length=10)),
                ('voltage', models.CharField(choices=[('11KV', '11 كيلو فولت'), ('380', '380 فولت'), ('220', '220 فولت'), ('24', '24 فولت')], default='220', help_text='الجهد الكهربائي', max_length=10)),
                ('ampacity', models.FloatField(default=0, help_text='الأمبير الكلي')),
                ('cable_quantity', models.PositiveIntegerField(default=1, help_text='عدد الكابلات')),
                ('cable_cross_section', models.FloatField(choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=2.5, help_text='مساحة مقطع الكابل (ملم²)')),
                ('neutral_cross_section', models.FloatField(blank=True, choices=[(1.5, '1.5 mm²'), (2.5, '2.5 mm²'), (4, '4 mm²'), (6, '6 mm²'), (10, '10 mm²'), (16, '16 mm²'), (25, '25 mm²'), (35, '35 mm²'), (50, '50 mm²'), (70, '70 mm²'), (95, '95 mm²'), (120, '120 mm²'), (150, '150 mm²'), (185, '185 mm²'), (240, '240 mm²'), (300, '300 mm²'), (400, '400 mm²'), (500, '500 mm²'), (630, '630 mm²')], default=0, help_text='مساحة مقطع المحايد (ملم²)', null=True)),
                ('cable_material', models.CharField(choices=[('copper', 'نحاس'), ('aluminum', 'ألومنيوم')], default='copper', help_text='نوع مادة الكابل (نحاس أو ألومنيوم)', max_length=10)),
                ('cable_length', models.FloatField(default=0, help_text='طول الكابل (متر)')),
                ('cable_path', models.CharField(choices=[('aerial', 'في الهواء'), ('buried', 'مدفون'), ('conduit', 'في أنابيب'), ('tray', 'في مجاري كابلات')], default='aerial', help_text='مسار الكابل (في الهواء أو مدفون)', max_length=10)),
                ('feeder_breaker', models.OneToOneField(blank=True, help_text='القاطع المغذي للوحة في اللوحة الأم (في حالة اللوحة الفرعية)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fed_panel', to='network.circuitbreaker')),
                ('main_breaker', models.OneToOneField(blank=True, help_text='القاطع العمومي للوحة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_as_main', to='network.circuitbreaker')),
                ('parent_panel', models.ForeignKey(blank=True, help_text='اللوحة الأم المغذية (في حالة اللوحة الفرعية)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_panels', to='network.panel')),
                ('power_source', models.ForeignKey(blank=True, help_text='مصدر الطاقة المغذي (في حالة اللوحة الرئيسية)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='network.powersource')),
            ],
            bases=(models.Model, network.models.CableMixin),
        ),
        migrations.AddField(
            model_name='load',
            name='panel',
            field=models.ForeignKey(blank=True, help_text='اللوحة المغذية للحمل', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='network.panel'),
        ),
        migrations.CreateModel(
            name='PanelBreaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breaker', models.ForeignKey(help_text='القاطع المتصل باللوحة', on_delete=django.db.models.deletion.CASCADE, related_name='breaker_panels', to='network.circuitbreaker')),
                ('panel', models.ForeignKey(help_text='اللوحة التي ينتمي إليها القاطع', on_delete=django.db.models.deletion.CASCADE, related_name='panel_breakers', to='network.panel')),
            ],
        ),
        migrations.AddField(
            model_name='panel',
            name='breakers',
            field=models.ManyToManyField(help_text='القواطع المتصلة باللوحة', related_name='panels', through='network.PanelBreaker', to='network.circuitbreaker'),
        ),
        migrations.DeleteModel(
            name='MainPanel',
        ),
        migrations.DeleteModel(
            name='MainPanelBreaker',
        ),
        migrations.DeleteModel(
            name='SubPanel',
        ),
        migrations.DeleteModel(
            name='SubPanelBreaker',
        ),
    ]
