# Generated by Django 5.1.7 on 2025-04-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_subpanel_main_panel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='breakers',
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='panel',
            field=models.ForeignKey(blank=True, help_text='اللوحة التي ينتمي إليها القاطع', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_breakers', to='network.panel'),
        ),
        migrations.DeleteModel(
            name='PanelBreaker',
        ),
    ]
