# Generated by Django 5.1.7 on 2025-04-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_panel_breakers_circuitbreaker_panel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='load',
            options={'verbose_name': 'حمل كهربائي', 'verbose_name_plural': 'الأحمال الكهربائية'},
        ),
        migrations.AddField(
            model_name='load',
            name='description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للحمل', null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='estimated_usage_hours',
            field=models.FloatField(default=8.0, help_text='عدد ساعات التشغيل اليومية المقدرة'),
        ),
        migrations.AddField(
            model_name='load',
            name='label',
            field=models.CharField(blank=True, help_text="علامة توضيحية للحمل (مثل 'إنارة الممر'، 'بلاجة الاستراحة')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='load_type',
            field=models.CharField(choices=[('machine', 'آلة صناعية'), ('service_panel', 'لوحة خدمة'), ('outlet', 'بلاجة أو مخرج كهربائي'), ('lighting', 'إنارة'), ('fan', 'مراوح'), ('screen', 'شاشات'), ('exhaust', 'شفاطات هواء'), ('ac', 'تكييف'), ('heater', 'سخان'), ('refrigerator', 'ثلاجات وتبريد'), ('motor', 'محركات'), ('pump', 'مضخات'), ('other', 'أخرى')], default='other', help_text='نوع الحمل (آلة، إنارة، شفاط، إلخ)', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='power_factor',
            field=models.FloatField(default=0.85, help_text='معامل القدرة (Power Factor) من 0 إلى 1'),
        ),
    ]
