# Generated by Django 5.1.7 on 2025-04-02 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_alter_load_options_load_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='circuitbreaker',
            options={'ordering': ['position'], 'verbose_name': 'قاطع كهربائي', 'verbose_name_plural': 'القواطع الكهربائية'},
        ),
        migrations.AlterModelOptions(
            name='panel',
            options={'ordering': ['name'], 'verbose_name': 'لوحة كهربائية', 'verbose_name_plural': 'اللوحات الكهربائية'},
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='feeding_breakers',
            field=models.ManyToManyField(blank=True, help_text='القواطع التي تغذي هذا القاطع', related_name='fed_breakers', to='network.circuitbreaker'),
        ),
        migrations.AddField(
            model_name='panel',
            name='description',
            field=models.TextField(blank=True, help_text='وصف إضافي', null=True),
        ),
        migrations.AddField(
            model_name='panel',
            name='location',
            field=models.CharField(blank=True, help_text='موقع اللوحة', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='breaker_role',
            field=models.CharField(choices=[('main', 'قاطع رئيسي'), ('sub_main', 'قاطع رئيسي فرعي'), ('distribution', 'قاطع توزيع')], default='distribution', help_text='دور القاطع (رئيسي، رئيسي فرعي، أو توزيع)', max_length=20),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='panel',
            field=models.ForeignKey(blank=True, help_text='اللوحة التي ينتمي إليها القاطع', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='breakers', to='network.panel'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='feeder_breaker',
            field=models.OneToOneField(blank=True, help_text='القاطع المغذي للوحة في اللوحة الأم (للوحات الفرعية)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fed_panel', to='network.circuitbreaker'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_type',
            field=models.CharField(choices=[('main', 'لوحة رئيسية'), ('sub_main', 'لوحة رئيسية فرعية'), ('sub', 'لوحة فرعية')], default='main', help_text='نوع اللوحة (رئيسية، رئيسية فرعية، أو فرعية)', max_length=10),
        ),
        migrations.AlterField(
            model_name='panel',
            name='parent_panel',
            field=models.ForeignKey(blank=True, help_text='اللوحة الأم المغذية (للوحات الفرعية)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_panels', to='network.panel'),
        ),
    ]
